const mangMayTinhBank = [
    {q: "Topology mạng nào mà tất cả các máy trạm chia sẻ chung một đường truyền chính?", a: "A", o: ["Bus Topology", "Star Topology", "Mesh Topology", "Hybrid Topology"]},
    {q: "Topology mạng cục bộ (LAN Topology) nào mà đường truyền của 1 máy trạm gặp sự cố sẽ không ảnh hưởng đường truyền các máy trạm khác?", a: "B", o: ["Bus Topology", "Star Topology", "Ring Topology", "Point-to-point Topology"]},
    {q: "Hệ thống mạng máy tính được phân loại cơ bản như sau:", a: "C", o: ["Mạng toàn cầu, mạng đô thị, mạng đường trục, mạng cục bộ.", "Mạng toàn cầu, mạng hình sao, mạng diện rộng, mạng cục bộ.", "Mạng toàn cầu, mạng đô thị, mạng diện rộng, mạng cục bộ.", "Mạng toàn cầu, mạng đô thị, mạng hình vòng, mạng hình tuyến."]},
    {q: "Phát biểu nào sai về ứng dụng của mạng máy tính ?", a: "D", o: ["Chia sẻ tài nguyên", "Trao đổi thông tin", "Quản lý hệ thống máy tính", "Quản lý hành vi người dùng"]},
    {q: "Một mạng máy tính là các máy độc lập kết nối và làm việc với nhau bởi 02 thông số?", a: "C", o: ["Đường truyền và tốc độ.", "Tốc độ và hệ điều hành.", "Đường truyền và quy ước truyền thông.", "Quy ước truyền thông và số lượng máy kết nối."]},
    {q: "Nếu phân loại mạng máy tính theo kỹ thuật chuyển mạch thì mạng máy tính được phân làm bao nhiêu loại?", a: "A", o: ["Mạng chuyển mạch kênh và mạng chuyển mạch gói.", "Mạng chuyển mạch cứng và mạng chuyển mạch mềm.", "Mạng chuyển mạch tín hiệu và mạng chuyển mạch gói.", "Mạng chuyển mạch dữ liệu và mạng chuyển mạch kênh."]},
    {q: "Trong quá trình cấu hình Access Point, người dùng chọn chế độ mã hóa WEP 64 bit, vậy tối thiểu người dùng phải nhập chiều dài của password (dạng hexadecimal) là bao nhiêu kí tự ?", a: "B", o: ["12", "10", "13", "16"]},
    {q: "Nếu lấy một địa chỉ lớp B để chia subnet với netmask là 255.255.240.0 thì có bao nhiêu subnets có thể sử dụng được?", a: "C", o: ["2", "8", "16", "32"]},
    {q: "Byte đầu tiên của một địa chỉ IP có dạng 10110111, địa chỉ này thuộc lớp nào?", a: "B", o: ["Lớp A", "Lớp B", "Lớp C", "Lớp D"]},
    {q: "Địa chỉ nào sau đây là địa chỉ broadcast của mạng lớp B?", a: "B", o: ["149.255.255.255/10", "149.6.255.255/16", "149.6.7.255/16", "149.6.7.0"]},
    {q: "Theo Luật An ninh mạng, 'Sự cố an ninh mạng' được hiểu là gì?", a: "A", o: ["Là sự việc xảy ra trên không gian mạng gây tổn hại nghiệm trọng trật tự, an toàn xã hội, quyền và lợi ích hợp pháp của cơ quan, tổ chức, cá nhân.", "Là tình trạng không gian mạng xuất hiện dấu hiệu đe dọa xâm phạm an ninh quốc gia, gây tổn hại nghiệm trọng trật tự, an toàn xã hội, quyền và lợi ích hợp pháp của cơ quan, tổ chức, cá nhân.", "Là hành vi sử dụng không gian mạng, công nghệ thông tin, phương tiện điện tử để vi phạm pháp luật về an ninh quốc gia, trật tự, an toàn xã hội.", "Là sự việc xảy ra trên không gian mạng khi có hành vi xâm phạm nghiêm trọng an ninh quốc gia."]},
    {q: "Đặc điểm của mạng Bus là gì?", a: "A", o: ["Dùng một trục cáp đơn duy nhất để kết nối", "Có một nút trung tâm", "Các nút nối thành vòng tròn", "Yêu cầu nhiều thiết bị mạng phức tạp"]},
    {q: "Thiết bị Hub hoạt động ở tầng nào của mô hình OSI?", a: "A", o: ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"]},
    {q: "Switch là thiết bị thông minh hơn Hub vì nó có khả năng?", a: "C", o: ["Tăng tốc độ Internet", "Cấp địa chỉ IP", "Chuyển dữ liệu dựa trên địa chỉ MAC", "Diệt virus"]},
    {q: "Địa chỉ 192.168.1.1 thuộc lớp nào?", a: "C", o: ["Lớp A", "Lớp B", "Lớp C", "Lớp D"]},
    {q: "Prefix /24 tương ứng với Subnet Mask nào?", a: "B", o: ["255.255.0.0", "255.255.255.0", "255.0.0.0", "255.255.255.255"]},
    {q: "Giao thức nào dùng để truyền tải trang web?", a: "D", o: ["FTP", "SMTP", "DNS", "HTTP"]},
    {q: "Mô hình OSI có bao nhiêu tầng?", a: "B", o: ["4 tầng", "7 tầng", "5 tầng", "9 tầng"]},
    {q: "Tầng nào chịu trách nhiệm định tuyến trong mô hình OSI?", a: "C", o: ["Physical", "Data Link", "Network", "Transport"]},
    {q: "Đơn vị dữ liệu ở tầng Transport gọi là?", a: "A", o: ["Segment", "Packet", "Frame", "Bit"]},
    {q: "Đơn vị dữ liệu ở tầng Data Link gọi là?", a: "C", o: ["Segment", "Packet", "Frame", "Bit"]},
    {q: "Giao thức DNS có chức năng gì?", a: "B", o: ["Cấp IP động", "Phân giải tên miền thành địa chỉ IP", "Gửi email", "Truyền file"]},
    {q: "Lớp địa chỉ IP nào dùng cho Multicast?", a: "D", o: ["Lớp A", "Lớp B", "Lớp C", "Lớp D"]},
    {q: "Địa chỉ MAC có bao nhiêu bit?", a: "C", o: ["32 bit", "128 bit", "48 bit", "64 bit"]},
    {q: "Cáp xoắn đôi UTP có bao nhiêu sợi đồng bên trong?", a: "D", o: ["2 sợi", "4 sợi", "6 sợi", "8 sợi"]},
    {q: "Đầu nối RJ-45 dùng cho loại cáp nào?", a: "B", o: ["Cáp quang", "Cáp xoắn đôi", "Cáp đồng trục", "Cáp điện thoại"]},
    {q: "Giao thức nào là giao thức tin cậy hướng kết nối?", a: "A", o: ["TCP", "UDP", "IP", "ICMP"]},
    {q: "Địa chỉ IP Loopback là địa chỉ nào?", a: "B", o: ["192.168.1.1", "127.0.0.1", "10.0.0.1", "8.8.8.8"]},
    {q: "Thiết bị nào dùng để kết nối các mạng khác nhau?", a: "C", o: ["Switch", "Hub", "Router", "Repeater"]},
    {q: "IPv6 có độ dài bao nhiêu bit?", a: "D", o: ["32 bit", "64 bit", "48 bit", "128 bit"]},
    {q: "Giao thức DHCP dùng để làm gì?", a: "A", o: ["Cấp IP động tự động", "Bảo mật mạng", "Quản lý tên miền", "Truyền tệp"]},
    {q: "WiFi chuẩn 802.11n hoạt động ở băng tần nào?", a: "C", o: ["2.4 GHz", "5 GHz", "Cả 2.4 GHz và 5 GHz", "900 MHz"]},
    {q: "Lệnh nào dùng để kiểm tra kết nối giữa hai máy tính?", a: "B", o: ["ipconfig", "ping", "tracert", "netstat"]},
    {q: "Giao thức SMTP dùng để?", a: "C", o: ["Nhận mail", "Tải file", "Gửi mail", "Duyệt web"]},
    {q: "Cáp quang truyền tín hiệu bằng?", a: "D", o: ["Điện áp", "Sóng vô tuyến", "Xung điện", "Ánh sáng"]},
    {q: "Subnet Mask mặc định của lớp A là?", a: "A", o: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"]},
    {q: "Hub gửi dữ liệu cho tất cả các cổng, cơ chế này gọi là?", a: "B", o: ["Unicast", "Broadcast", "Multicast", "Anycast"]},
    {q: "Dải địa chỉ Private lớp A là?", a: "C", o: ["192.168.x.x", "172.16.x.x", "10.x.x.x", "127.x.x.x"]},
    {q: "Tầng 4 của mô hình OSI là tầng nào?", a: "D", o: ["Physical", "Network", "Session", "Transport"]},
    {q: "Firewall (Tường lửa) có tác dụng gì?", a: "B", o: ["Tăng tốc độ mạng", "Kiểm soát và ngăn chặn truy cập trái phép", "Cấp địa chỉ IP", "Lưu trữ dữ liệu"]},
    {q: "Chuẩn mạng LAN phổ biến nhất hiện nay là?", a: "A", o: ["Ethernet", "Token Ring", "FDDI", "ATM"]},
    {q: "Telnet là giao thức dùng để?", a: "C", o: ["Gửi file", "Duyệt web", "Điều khiển máy tính từ xa", "Chat"]},
    {q: "Tầng nào của OSI đảm bảo truyền tin cậy giữa hai máy?", a: "D", o: ["Network", "Physical", "Data Link", "Transport"]},
    {q: "Địa chỉ IP có dạng 172.16.0.1 thuộc lớp nào?", a: "B", o: ["Lớp A", "Lớp B", "Lớp C", "Lớp D"]},
    {q: "Giao thức FTP sử dụng cổng (Port) bao nhiêu?", a: "C", o: ["80", "443", "20, 21", "25"]},
    {q: "Khi một máy trạm trong mạng Bus bị hỏng, điều gì xảy ra?", a: "A", o: ["Toàn bộ mạng có thể bị ngừng hoạt động", "Chỉ máy đó không vào mạng được", "Mạng vẫn chạy bình thường", "Mạng sẽ nhanh hơn"]},
    {q: "IEEE 802.3 là chuẩn cho mạng nào?", a: "B", o: ["Mạng không dây", "Mạng Ethernet có dây", "Mạng Bluetooth", "Mạng Token Ring"]},
    {q: "Mạng máy tính đô thị có tên viết tắt là?", a: "C", o: ["LAN", "WAN", "MAN", "PAN"]},
    {q: "Công thức tính số lượng Host tối đa trong mạng con n bit host?", a: "B", o: ["2^n", "2^n - 2", "2^n + 2", "2^n"]},
    {q: "Byte đầu tiên địa chỉ IP lớp D nằm trong khoảng nào?", a: "D", o: ["1-126", "128-191", "192-223", "224-239"]},
    {q: "Lệnh Tracert dùng để?", a: "B", o: ["Xem IP máy", "Kiểm tra đường đi gói tin", "Xóa cache", "Xóa virus"]},
    {q: "Proxy Server có nhiệm vụ chính là gì?", a: "D", o: ["Định tuyến", "Cấp IP", "Mã hóa", "Ủy thác kết nối và lưu trữ đệm"]},
    {q: "SSH hoạt động ở port mặc định nào?", a: "A", o: ["22", "23", "80", "443"]},
    {q: "Mã hóa WEP 128 bit yêu cầu bao nhiêu ký tự Hex?", a: "D", o: ["10", "13", "16", "26"]},
    {q: "Switch hoạt động dựa trên bảng nào?", a: "C", o: ["Bảng IP", "Bảng Route", "Bảng MAC (CAM table)", "Bảng Host"]},
    {q: "Tầng nào thực hiện việc đóng gói dữ liệu thành Packet?", a: "B", o: ["Data Link", "Network", "Transport", "Physical"]},
    {q: "VPN là viết tắt của?", a: "A", o: ["Virtual Private Network", "Visual Private Net", "Virtual Public Network", "Visual Public Net"]},
    {q: "Giao thức nào dùng để nhận email từ server?", a: "C", o: ["SMTP", "HTTP", "POP3/IMAP", "SNMP"]},
    {q: "Bit đầu tiên của lớp B luôn là?", a: "B", o: ["0", "10", "110", "1110"]},
    {q: "Tổ chức nào cấp phát địa chỉ IP toàn cầu?", a: "C", o: ["IEEE", "ISO", "IANA/ICANN", "Microsoft"]},
    {q: "Subnet mask /16 tương ứng với?", a: "B", o: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"]},
    {q: "Dịch vụ DNS dùng port nào?", a: "A", o: ["53", "80", "443", "25"]},
    {q: "Ping sử dụng giao thức nào?", a: "C", o: ["TCP", "UDP", "ICMP", "ARP"]},
    {q: "Địa chỉ 255.255.255.255 là địa chỉ?", a: "B", o: ["IP tĩnh", "Limited Broadcast", "Multicast", "Private"]},
    {q: "MAC Address thuộc tầng nào của OSI?", a: "A", o: ["Data Link", "Network", "Physical", "Transport"]},
    {q: "Modem có chức năng chính là gì?", a: "B", o: ["Định tuyến", "Điều chế và giải điều chế tín hiệu", "Lọc nội dung", "Cấp IP"]},
    {q: "Chuẩn 802.11ac là chuẩn cho?", a: "C", o: ["Mạng LAN", "Mạng WAN", "WiFi tốc độ cao", "Bluetooth"]},
    {q: "Tầng nào xử lý lỗi và điều khiển luồng dữ liệu?", a: "D", o: ["Physical", "Application", "Network", "Transport"]},
    {q: "Định nghĩa 'Nguy cơ an ninh mạng' theo Luật ANM là gì?", a: "B", o: ["Sự cố phần cứng", "Tình trạng xuất hiện dấu hiệu đe dọa xâm phạm ANQG", "Hành vi sai phạm", "Lỗi phần mềm"]},
    {q: "Cáp chéo dùng để nối?", a: "A", o: ["Hai thiết bị cùng loại (PC-PC)", "PC-Switch", "Switch-Router", "PC-Hub"]},
    {q: "Băng thông mạng được đo bằng đơn vị?", a: "C", o: ["Hz", "Byte", "bps (bits per second)", "RPM"]},
    {q: "Gateway có chức năng gì?", a: "B", o: ["Tăng sóng", "Kết nối hai mạng khác giao thức", "Cấp IP", "Chia cổng"]},
    {q: "Lớp C có bao nhiêu bit làm Network ID mặc định?", a: "D", o: ["8 bit", "16 bit", "20 bit", "24 bit"]},
    {q: "Cổng mặc định giúp máy tính làm gì?", a: "A", o: ["Đi ra ngoài mạng LAN", "Vào mạng nội bộ", "Bảo mật", "Tăng tốc"]},
    {q: "Tầng nào trong OSI mã hóa dữ liệu?", a: "C", o: ["Session", "Application", "Presentation", "Data Link"]},
    {q: "Địa chỉ IP nào là địa chỉ mạng (Network Address)?", a: "B", o: ["192.168.1.1", "192.168.1.0", "192.168.1.255", "0.0.0.1"]},
    {q: "Cáp xoắn đôi STP khác UTP ở điểm nào?", a: "D", o: ["Rẻ hơn", "Dễ uốn", "Nhanh hơn", "Có lớp bọc chống nhiễu"]},
    {q: "Router tìm đường đi dựa trên bảng nào?", a: "A", o: ["Routing Table", "ARP Table", "MAC Table", "DNS Table"]},
    {q: "Giao thức UDP là giao thức?", a: "B", o: ["Tin cậy", "Không hướng kết nối (Connectionless)", "Mã hóa cao", "Dành cho web"]},
    {q: "Port 443 dùng cho dịch vụ?", a: "C", o: ["HTTP", "FTP", "HTTPS", "DNS"]},
    {q: "Kỹ thuật dùng một IP public cho nhiều máy LAN?", a: "A", o: ["NAT", "DHCP", "DNS", "VLAN"]},
    {q: "ARP dùng để tìm địa chỉ nào?", a: "C", o: ["Địa chỉ IP", "Địa chỉ Port", "Địa chỉ MAC", "Địa chỉ Mail"]},
    {q: "Phạm vi mạng WAN là?", a: "D", o: ["Một phòng", "Một tòa nhà", "Một thành phố", "Quốc gia hoặc toàn cầu"]},
    {q: "Topology nào tốn nhiều dây cáp nhất?", a: "B", o: ["Bus", "Full Mesh", "Star", "Ring"]},
    {q: "Tầng vật lý truyền dữ liệu dưới dạng?", a: "A", o: ["Bit stream", "Frame", "Packet", "Segment"]},
    {q: "Địa chỉ IP lớp A có NetID là bao nhiêu bit?", a: "B", o: ["4 bit", "8 bit", "16 bit", "24 bit"]},
    {q: "Tại sao cần chia Subnet?", a: "C", o: ["Để mua thêm IP", "Để mạng chạy chậm lại", "Để quản lý mạng dễ dàng và tiết kiệm IP", "Không cần thiết"]},
    {q: "WiFi 5GHz có ưu điểm gì so với 2.4GHz?", a: "A", o: ["Tốc độ cao hơn, ít nhiễu", "Sóng đi xa hơn", "Xuyên tường tốt hơn", "Rẻ hơn"]},
    {q: "Thành phần nào không thuộc 1 hệ thống mạng máy tính?", a: "D", o: ["Thiết bị đầu cuối", "Đường truyền", "Giao thức", "Hệ điều hành đơn lẻ"]},
    {q: "An ninh mạng là bảo vệ gì?", a: "B", o: ["Chỉ bảo vệ máy tính", "Bảo vệ thông tin, hệ thống trên không gian mạng", "Bảo vệ mật khẩu", "Bảo vệ dây cáp"]},
    {q: "Thiết bị Bridge hoạt động ở tầng nào?", a: "C", o: ["Physical", "Network", "Data Link", "Transport"]},
    {q: "ICMP viết tắt của?", a: "A", o: ["Internet Control Message Protocol", "Intranet Control Message Protocol", "Internet Connect Mail Protocol", "Internal Control Main Protocol"]},
    {q: "Địa chỉ 10.0.0.5 thuộc mạng nào?", a: "B", o: ["Public", "Private", "Loopback", "Multicast"]},
    {q: "Cáp đồng trục hiện nay ít dùng trong LAN vì?", a: "D", o: ["Quá nhanh", "Quá rẻ", "Quá nhỏ", "Khó thi công và tốc độ thấp hơn cáp xoắn"]},
    {q: "Dịch vụ DHCP giúp tránh lỗi gì?", a: "C", o: ["Lỗi virus", "Lỗi mất mạng", "Lỗi trùng địa chỉ IP", "Lỗi hỏng Switch"]},
    {q: "Chuẩn nén ảnh JPEG thuộc tầng nào của OSI?", a: "B", o: ["Application", "Presentation", "Session", "Physical"]},
    {q: "Một mạng có 2 máy tính nối trực tiếp là mạng?", a: "A", o: ["Peer-to-Peer", "Client-Server", "Mainframe", "Cloud"]},
    {q: "TCP/IP là gì?", a: "C", o: ["Một loại máy tính", "Một phần mềm", "Một bộ giao thức truyền thông", "Một hệ điều hành"]},
    {q: "Địa chỉ IPv4 có bao nhiêu Byte?", a: "B", o: ["2 Byte", "4 Byte", "6 Byte", "8 Byte"]},
    {q: "Trong quá trình cấu hình Access Point, người dùng chọn WEP 64 bit, độ dài password hexa là?", a: "B", o: ["12", "10", "13", "16"]}
];